export const strings = {
  USER_CREATED: "USER_CREATED",
  LOGIN_SUCESSFUL: "LOGIN_SUCESSFUL",
  USER_ALREADY_LOGGED_IN: "USER_ALREADY_LOGGED",
  USER_DISCONNECTED: "USER_DISCONNECTED",
  SOMETHING_WAS_WRONG: "SOMETHING_WAS_WRONG",
  EMAIL_PASSWORD_INVALID: "EMAIL_PASSWORD_INVALID",
  INVALID_PASSWORD: "PASSWORD_INVALID",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  UNAUTHORIZED: "UNAUTHORIZED",
  PAGE_NOT_FOUND: "PAGE_NOT_FOUND",
  NEED_AUTHENTICATION: "NEED_AUTHENTICATION",
  SUCCESSFUL_OPERATION: "SUCCESSFUL_OPERATION",
  EMPTY_LIST: "EMPTY_LIST",
  USER_NOT_FOUND: "USER_NOT_FOUND"
}

export const plurals = {
  MISSING_ATRIBUTES: "MISSING_ATTRIBUTES",
  INVALID_ATTRIBUTES: "INVALID_ATTRIBUTES",
  LINK_ALREADY_EXISTS: "LINK_ALREADY_EXISTS",
  SERVICE_ONLINE: "SERVICE_ONLINE"
}