export const strings = {
  USER_CREATED: "USER_CREATED",
  LOGIN_SUCESSFUL: "LOGIN_SUCESSFUL",
  USER_ALREADY_LOGGED_IN: "USER_ALREADY_LOGGED",
  USER_DISCONNECTED: "USER_DISCONNECTED",
  SOMETHING_WAS_WRONG: "SOMETHING_WAS_WRONG",
  EMAIL_PASSWORD_INVALID: "EMAIL_PASSWORD_INVALID",
  INVALID_EMAIL: "INVALID_EMAIL",
  INVALID_PASSWORD: "PASSWORD_INVALID",
  INVALID_GENDER: "INVALID_GENDER",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  NO_USER_LOGGED_IN: "NO_USER_LOGGED_IN",
  UNAUTHORIZED: "UNAUTHORIZED",
  PAGE_NOT_FOUND: "PAGE_NOT_FOUND",
  NEED_AUTHENTICATION: "NEED_AUTHENTICATION"
}

export const plurals = {
  MISSING_ATRIBUTES: "MISSING_ATTRIBUTES"
}